AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  risk_engine

  Sample SAM Template for lambda-python3.11

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
  Api:
    BinaryMediaTypes:
      - "*/*"

Resources:
  UploadBusinessOverview:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.upload_business_overview
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: 'canyouhackit'
      Environment:
        Variables:
          BUCKET_NAME: 'canyouhackit'
          OPENAI_API_KEY: 'HERE OPENAI API KEY'
      Events:
        UploadEvent:
          Type: Api
          Properties:
            Path: /business-overview
            Method: post
  FormSubmissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: forms.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FundingRequestsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref FundingRequestsTable
      Events:
        SubmitForm:
          Type: Api
          Properties:
            Path: /submit-form
            Method: post
  FundingRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: wonderlend_skynet
      AttributeDefinitions:
        - AttributeName: RequestId
          AttributeType: S
      KeySchema:
        - AttributeName: RequestId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  

  

          

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RiskEngineApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  FormApi:
    Description: "API Gateway endpoint URL for Prod stage for Form Submission function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submit-form/"
  FormFunction:
    Description: "Form Submission Lambda Function ARN"
    Value: !GetAtt FormSubmissionFunction.Arn
  FormFunctionIamRole:
    Description: "Implicit IAM Role created for Form Submission function"
    Value: !GetAtt FormSubmissionFunctionRole.Arn
  UploadBusinessOverview:
    Description: "UploadBusinessOverview Lambda Function ARN"
    Value: !GetAtt UploadBusinessOverview.Arn
 
