AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  risk_engine

  Sample SAM Template for lambda-python3.11

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
  Api:
    BinaryMediaTypes:
      - "*/*"
    Cors:
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  OptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: risk_engine/
      Handler: app.option_handler
      Runtime: python3.11
      Events:
        OptionsRiskEvent:
          Type: Api
          Properties:
            Path: /risk/report
            Method: options
        OptionsUploadBEvent:
          Type: Api
          Properties:
            Path: /upload/business
            Method: options
        OptionsUploadFEvent:
          Type: Api
          Properties:
            Path: /upload/financial
            Method: options
        OptionsUploadCEvent:
          Type: Api
          Properties:
            Path: /upload/compliance
            Method: options
            
  UploadBusinessOverview:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: risk_engine/
      Handler: app.upload_business_overview
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: 'canyouhackit'
      Environment:
        Variables:
          BUCKET_NAME: 'canyouhackit'
      Events:
        UploadEvent:
          Type: Api
          Properties:
            Path: /upload/business
            Method: post
  UploadFinancialStatements:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: risk_engine/
      Handler: app.upload_financial_statements
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: 'canyouhackit'
      Environment:
        Variables:
          BUCKET_NAME: 'canyouhackit'
          OPENAI_API_KEY: 'canyouhackit'
      Events:
        UploadEvent:
          Type: Api
          Properties:
            Path: /upload/financial
            Method: post
  UploadCompliance:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: risk_engine/
      Handler: app.upload_compliance
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: 'canyouhackit'
      Environment:
        Variables:
          BUCKET_NAME: 'canyouhackit'
          OPENAI_API_KEY: 'canyouhackit'
      Events:
        UploadEvent:
          Type: Api
          Properties:
            Path: /upload/compliance
            Method: post

  RiskReport:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: risk_engine/
      Handler: app.risk_report
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: 'canyouhackit'
      Environment:
        Variables:
          BUCKET_NAME: 'canyouhackit'
          OPENAI_API_KEY: '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'
      Events:
        UploadEvent:
          Type: Api
          Properties:
            Path: /risk/report
            Method: post

  FormSubmissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: forms.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FundingRequestsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref FundingRequestsTable
      Events:
        SubmitForm:
          Type: Api
          Properties:
            Path: /submit-form
            Method: post
  FundingRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: wonderlend_skynet
      AttributeDefinitions:
        - AttributeName: RequestId
          AttributeType: S
      KeySchema:
        - AttributeName: RequestId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  

  

          

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RiskEngineApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FormApi:
    Description: "API Gateway endpoint URL for Prod stage for Form Submission function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submit-form/"
  FormFunction:
    Description: "Form Submission Lambda Function ARN"
    Value: !GetAtt FormSubmissionFunction.Arn
  FormFunctionIamRole:
    Description: "Implicit IAM Role created for Form Submission function"
    Value: !GetAtt FormSubmissionFunctionRole.Arn
  UploadBusinessOverview:
    Description: "UploadBusinessOverview Lambda Function ARN"
    Value: !GetAtt UploadBusinessOverview.Arn
 
